name: 'Generate JavaScript code and open pull request with it'

on:
  push:
    branches-ignore:
      - 'renovate/*'
      - 'github-actions/generate-js/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          version: 8.x.x

      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install

      - run: pnpm run prepare

      - name: Create pull request with generated JavaScript
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7.0.11
        with:
          add-paths: |
            dist/
            pnpm-lock.yaml
          commit-message: Generate JavaScript based on ${{ github.sha }}
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: github-actions/generate-js/${{ github.ref_name }}
          title: Generate JavaScript for branch `${{ github.ref_name }}`
          body: |
            This pull request is opened automatically and contains generated JavaScript code based on commit ${{ github.sha }}.
