name: 'Generate JavaScript code and open pull request with it'

on:
  push:
    branches-ignore:
      - 'renovate/*'
      - 'github-actions/generate-js/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        with:
          version: 10.x

      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install

      - run: pnpm run prepare

      - name: Create pull request with generated JavaScript
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          add-paths: |
            dist/
            pnpm-lock.yaml
          commit-message: Generate JavaScript based on ${{ github.sha }}
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: github-actions/generate-js/${{ github.ref_name }}
          title: Generate JavaScript for branch `${{ github.ref_name }}`
          body: |
            This pull request is opened automatically and contains generated JavaScript code based on commit ${{ github.sha }}.
