name: 'Generate JavaScript code and open Pull request with it'

on:
  push:
    branches:
     - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - run: npm install

      - run: npm run prepare

      - name: Create Pull Request with generated JavaScript
        uses: peter-evans/create-pull-request@v5
        with:
          add-paths: dist/
          commit-message: Generate JavaScript
          title: Generate JavaScript
          body: |
            This Pull Request is opened automatically and contains generated JavaScript code based on pushed changes.
